version: '3'
services:

  my-spring:
    image: amazoncorretto:8u202
    ports:
      - 8080:8080
      - 5005:5005
    volumes:
      - .:/work
      - ${HOME}/.m2:/root/.m2
    working_dir: /work
    command: >
      ./mvnw spring-boot:run
      -Drun.jvmArguments="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005"
    environment:
      JAVA_HOME: /usr/lib/jvm/java

  my-db:
    image: mysql:5.7.25
    ports:
      - 3306:3306
    volumes:
      - ./src/test/resources/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
